### ISSUE TITLE
Asignacion de utilidad por grupo y precio

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_admin#2]
Actualmente existe esta funcionalidad, pero el proceso no es el adecuado, ya que hay que ir seleccionando cada grupo, cada precio y asignandole la utilidad, la idea es listar el grupo y de una vez poner la utilidad a todos los precios activos

**Comment by angelvcuenca** [comment]
La asignación de utilidad por grupo y precio se encuentra concluida, se creo nuevas vistas y se agrego nuevas funciones en el controlador para poder llevar a cabo el funcionamiento de los solicitado
