### ISSUE TITLE
CONTROLAR QUE SOLO SUPER USUARIO PUEDA CREAR BODEGAS Y PUNTOS DE VENTA 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_admin#8]
EL BILLINGSOFT tiene varias versiones y es importante que se pueda controlar la creacion de bodegas y puntos de venta ya que el cliente segun la version se le puede otorgar determiando numero de bodegas y puntos de venta

**Comment by dannyjimenez110** [comment]
Revisar si se cumple con el requerimiento
